// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.join(process.cwd(), ".env") });
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
    throw new Error("DATABASE_URL environment variable is not set");
}

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    // Removed 'engine: "classic",' as it's not a valid property in PrismaConfig.
    // If you need to specify the engine type, do so in prisma/schema.prisma under the generator block, e.g.:
    // generator client {
    //   engineType = "library"
    // }
    datasource: {
        url: databaseUrl,
    },
});